### ISSUE TITLE
Starting temp is not set correctly and direction is misleading

### ISSUE THREAD

**Issue by enebybrygg** [fchorney/CuraPlugins#1]
Starting temperature is actually set to the init value minus the increment. It should be set to the user specified starting temperature and only later (at higher Z value) be changed. Also it is hard to understand the direction of temp change if the setting is documented as a temperature adjustment. You would normally read that as if the temp value changes in the same direction as the Z-value.

**Comment by fchorney** [comment]
Hi, thanks for the comment. In my experience the first issue you mention is how it seems to be working for me. The initial temperature always seems to be the temperature that is set in cura itself (which would be the highest temperature you want to test according to the temperature script), so I'm not quite sure why that part isn't working for you. The script doesn't actually insert any temperature change gcode lines until the first height increment. 

I'm not sure from where you found this github page, but if it wasn't from thingiverse, my page on it has a better explanation on how it all works https://www.thingiverse.com/thing:2687375 

I'm not too sure what you mean with your second point either, as the instructions state that temperature will decrease as height goes up. Let me know if there is anything else I could change or clear up for you and I would be happy to do so. Thanks!

**Comment by enebybrygg** [comment]
Thanks for the reply!
Regarding the first point I think the parameter start temperature should be used. Is it not better to simply override the setting in the cura profile? Otherwise the current tooltip is very misleading talking about initial nozzle temp.Regarding the second point you labelled the parameter Temperature Increment. I was also confused by the name of the variable in the python code also named increase.
Cheers!


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Fernando Chorney <notifications@github.com> 
Datum: 2018-01-16  16:11  (GMT+01:00) 
Till: DJSymBiotiX/CuraPlugins <CuraPlugins@noreply.github.com> 
Kopia: Håkan Westrin <hakan@westrins.se>, Author <author@noreply.github.com> 
Rubrik: Re: [DJSymBiotiX/CuraPlugins] Starting temp is not set correctly and
  direction is misleading (#1) 

Hi, thanks for the comment. In my experience the first issue you mention is how it seems to be working for me. The initial temperature always seems to be the temperature that is set in cura itself (which would be the highest temperature you want to test according to the temperature script), so I'm not quite sure why that part isn't working for you. The script doesn't actually insert any temperature change gcode lines until the first height increment.
I'm not sure from where you found this github page, but if it wasn't from thingiverse, my page on it has a better explanation on how it all works https://www.thingiverse.com/thing:2687375
I'm not too sure what you mean with your second point either, as the instructions state that temperature will decrease as height goes up. Let me know if there is anything else I could change or clear up for you and I would be happy to do so. Thanks!

**Comment by fchorney** [comment]
Hi, I'm not sure this matters to you anymore at this point, but both your issues have been fixed in my latest change to the Temp script. The initial temperature is set properly, and I have changed the name of the temperature variable to "temperature decrease" instead of "increase". I hope that helps!
